DROP TABLE IF EXISTS TBL_VENDOR_HEALTH_DETAILS;
DROP TABLE IF EXISTS TBL_VENDOR_HEALTH_CONFIG;

CREATE TABLE TBL_VENDOR_HEALTH_DETAILS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VENDOR_CD TEXT NOT NULL,
    HEALTHSTATUS TEXT NOT NULL,
    CONSECUTIVEERRORCOUNT INTEGER NOT NULL DEFAULT 0,
    LastFailureTime TEXT,
    LastSuccessTime TEXT,
    DownSince TEXT,
    UpdatedOn TEXT
);

CREATE TABLE TBL_VENDOR_HEALTH_CONFIG (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FAILURETHRESHOLDCOUNT INTEGER NOT NULL,
    SUCCESSTHRESHOLDCOUNT INTEGER NOT NULL,
    HEALTHCHECKINTERVAL_MIN INTEGER NOT NULL,
    IS_HEALTHCHECK_ENABLED INTEGER NOT NULL DEFAULT 1,
    CREATED_BY TEXT,
    CREATED_ON TEXT,
    UPDATED_BY TEXT,
    UPDATED_ON TEXT
);
