DROP TABLE IF EXISTS SUCCESS_MESSAGES;

CREATE TABLE SUCCESS_MESSAGES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MSG_ID TEXT,
    DEPT_ID TEXT,
    APP_ID TEXT,
    MOBILE_NO TEXT,
    MSG_TEXT TEXT,
    PIN TEXT,
    POP_MAIL_ID TEXT,
    POP_SENDER_ADDR TEXT,
    TSG_DETAILS TEXT,
    CHANNEL TEXT,
    VENDOR_CD TEXT,
    SEND_COUNT TEXT,
    TOPIC_NAME TEXT,
    ACK_ID TEXT,
    VENDOR_RESPONSE TEXT,
    DEPT_ID_OLD TEXT,
    APP_ID_OLD TEXT
);
