spring.application.name=FailedMicroservice

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:failed-demo.db
spring.sql.init.mode=always

failed.kafka.bootstrap-servers=localhost:9092
failed.kafka.topic=smsgw.failed
failed.kafka.group-id=failed-microservice-group

logging.level.com.icici.failedmicroservice=INFO
