spring.application.name=SuccessMicroservice

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:success-demo.db
spring.sql.init.mode=always

success.kafka.bootstrap-servers=localhost:9092
success.kafka.topic=smsgw.success
success.kafka.group-id=success-microservice-group

logging.level.com.icici.successmicroservice=INFO
