DROP TABLE IF EXISTS DED_MESSAGES;

CREATE TABLE DED_MESSAGES (
    MSG_ID TEXT,
    DEPT_ID TEXT,
    APP_ID TEXT,
    MOBILE_NO TEXT,
    ERR_DESC TEXT,
    ERROR_SOURCE TEXT,
    ERR_DTTIME TEXT,
    ERR_STACK_TRACE TEXT,
    ERR_VENDOR_CODE TEXT,
    REQUEST_PARAM TEXT,
    TSG_DETAILS TEXT,
    CHANNEL TEXT,
    VENDOR_CD TEXT,
    TOPIC_NAME TEXT
);
